spring:
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/moradores
    user: root
    password: 0000
    locations: classpath:/mnt/wwn-0x50014ee214f4aa7a-part1/Projetos/sql -baselineOnMigrate=true

