flyway.url=jdbc:mysql://127.0.0.1:3306/moradores
flyway.user=root
flyway.password=0000
flyway.locations=filesystem:/mnt/wwn-0x50014ee214f4aa7a-part1/Projetos/FechaduraDigital/target/classes
flyway.schemas=moradores
